
import Head from 'next/head'


interface IProps {
  title: string;
  description?: string;
}

function HeadMeta({title, description}: IProps) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description && "Generated by create next app"} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadMeta